### ISSUE TITLE
Use wildcard whitelists for federation

### ISSUE THREAD

**Issue by addshore** [wbstack/queryservice#2]
> Whitelist wildcard support added in https://phabricator.wikimedia.org/T196858
> Apparently https://phabricator.wikimedia.org/T226603 is also needed

This would allow federating between all of the *.opencura wikibases?
Though not custom domains? :/

For that a different solution would be needed where the whitelist could be dynamically grabbed?

**Comment by deer-wmde** [comment]
moved https://phabricator.wikimedia.org/T357106
